---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: palworld
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
      - name: palworld-server
        image: thijsvanloef/palworld-server-docker:v0.37.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "4"
            memory: "24Gi"
            ephemeral-storage: "20Gi"
        ports:
        - containerPort: 8211
          name: server
          protocol: UDP
        - containerPort: 27015
          name: query
          protocol: UDP
        - containerPort: 25575
          name: rcon
          protocol: TCP
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: admin-password
        - name: SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: server-password
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: palworld-secrets
              key: discord-webhook-url
        envFrom:
        - configMapRef:
            name: palworld-cm
        volumeMounts:
        - mountPath: /palworld
          name: datadir
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: palworld-server-datadir
