---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-secrets
  namespace: palworld
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: palworld-secrets
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      key: palworld-secrets
      property: admin-password
  - secretKey: server-password
    remoteRef:
      key: palworld-secrets
      property: server-password
  - secretKey: discord-webhook-url
    remoteRef:
      key: palworld-secrets
      property: discord-webhook-url
