apiVersion: v1
kind: Service
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: palworld
spec:
  ports:
    - name: server
      port: 8211
      protocol: UDP
      targetPort: server
      nodePort: 30001
    - name: query
      port: 27015
      protocol: UDP
      targetPort: query
      nodePort: 30002
    - name: rcon
      port: 25575
      targetPort: rcon
      nodePort: 30003
  selector:
    app: palworld-server
  type: NodePort
