---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
    cert-manager.io/private-key-algorithm: "ECDSA"
    cert-manager.io/private-key-size: "384"
    nginx.ingress.kubernetes.io/proxy-body-size: "4g"
    nginx.ingress.kubernetes.io/limit-connections: "100"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-rpm: "500"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "10"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
  name: growi-converter-ingress
  namespace: growi-converter
spec:
  ingressClassName: nginx
  rules:
  - host: growi-converter.i-tk.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: growi-converter
            port:
              name: http
  tls:
  - hosts:
    - growi-converter.i-tk.dev
    secretName: growi-converter-itk-dev-secret
