---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: growi
resources:
- cronjob.yaml
- pvc-backup-dir.yaml
- pvc-attachments-dir.yaml
configMapGenerator:
  - name: cm-backup
    files:
      - ./config/backup.sh
