---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-converter
  labels:
    app: growi-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growi-converter
  template:
    metadata:
      labels:
        app: growi-converter
    spec:
      containers:
      - name: growi-converter
        image: ghcr.io/itk13201/growi-converter:v1.1.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: growi-converter-cm
        env:
        - name: GROWI_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: growi-converter-secret
              key: growi-api-token
        - name: GROWI_API_URL
          valueFrom:
            secretKeyRef:
              name: growi-converter-secret
              key: growi-api-url
        volumeMounts:
        - name: attachment
          mountPath: "/attachment"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: attachment
        persistentVolumeClaim:
          claimName: growi-converter-attachment-pvc
