---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: growi-converter-secret
  namespace: growi-converter
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: growi-converter-secret
    creationPolicy: Owner
  data:
  - secretKey: growi-api-token
    remoteRef:
      key: growi-converter-secret
      property: growi-api-token
  - secretKey: growi-api-url
    remoteRef:
      key: growi-converter-secret
      property: growi-api-url
