---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: growi-converter-attachment-pvc
  labels:
    app: growi-converter
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual
  selector:
    matchLabels:
      target-app: growi-converter-attachment
