---
apiVersion: v1
kind: Service
metadata:
  name: growi-converter
  labels:
    app: growi-converter
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: growi-converter
