repos:
  - repo: local
    hooks:
      - id: check-diff-of-same-deployment-files
        name: check-diff-of-same-deployment-files
        entry: bash ./scripts/check_diff_of_same_deployment_files.sh
        language: system
        pass_filenames: false
