---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calendarrabbit-mysql-pv
  labels:
    target-app: calendarrabbit-mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd/data/k8s/pv/calendarrabbit/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
