---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-converter-attachment-pv
  labels:
    target-app: growi-converter-attachment
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd/data/k8s/pv/growi-converter/attachment
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
