---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-mongoexport-backup-pv
  labels:
    target-app: growi-mongoexport-backup
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd/data/k8s/pv/growi/mongoexport-backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
