---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-backup-backup-dir-pv
  labels:
    target-app: growi-backup-backup-dir
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd-backup/backups/k8s/pv/growi-backup/backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
