---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailserver-config-pv
  labels:
    target-app: mailserver-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd/data/k8s/pv/mailserver/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
