---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moneyrabbit-mariadb-pv
  labels:
    target-app: moneyrabbit-mariadb
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd/data/k8s/pv/moneyrabbit/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
