apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis-pv
  labels:
    target-app: nextcloud-redis
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    # path: /data/k8s/pv/nextcloud/redis
    path: /mnt/hdd/data/k8s/pv/nextcloud/redis
