---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis-master-pv
  labels:
    target-app: nextcloud-redis-master
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd/data/k8s/pv/nextcloud/redis-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
