apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb-pv
  labels:
    target-app: nextcloud-mariadb
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    # path: /data/k8s/pv/nextcloud/mariadb
    path: /mnt/hdd/data/k8s/pv/nextcloud/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
