---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rss-generator-mariadb-primary-pv
  labels:
    target-app: rss-generator-mariadb-primary
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/hdd/data/k8s/pv/rss-generator/mariadb-primary
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
