apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: tkik13201@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X2"
    solvers:
      - dns01:
          cloudflare:
            apiKeySecretRef:
              name: cloudflare-secret
              key: API_KEY
            email: tkik13201@gmail.com
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: tkik13201@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X2"
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-secret
              key: API_KEY
            email: tkik13201@gmail.com
