---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-cloudflare-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cert-manager-cloudflare-secret
    creationPolicy: Owner
  data:
  - secretKey: API_KEY
    remoteRef:
      key: cert-manager-cloudflare-secret
      property: API_KEY
