---
all:
  children:
    control_plane:
      hosts:
        cp01:
          ansible_host: 192.168.1.200  # terraform output control_plane_ip
    workers:
      hosts:
        worker01:
          ansible_host: 192.168.1.201  # terraform output worker_ips[0]
