{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gomi-no-hi.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gomi-no-hi.labels" . | nindent 4 }}
type: Opaque
stringData:
  VAPID_PUBLIC_KEY: {{ .Values.backend.vapid.publicKey | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.backend.vapid.privateKey | quote }}
  VAPID_SUBJECT: {{ .Values.backend.vapid.subject | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
{{- end }}
