apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gomi-no-hi.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gomi-no-hi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "gomi-no-hi.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gomi-no-hi.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "gomi-no-hi.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: frontend
          image: {{ include "gomi-no-hi.frontendImage" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
