apiVersion: v1
kind: Service
metadata:
  name: {{ include "gomi-no-hi.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gomi-no-hi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "gomi-no-hi.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
