{{- if not .Values.redis.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gomi-no-hi.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gomi-no-hi.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
{{- end }}
