---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
helmCharts:
- name: nextcloud
  repo: https://nextcloud.github.io/helm/
  releaseName: nextcloud
  namespace: nextcloud
  version: 9.0.6
  valuesFile: values.yaml
  valuesMerge: override
images:
- name: docker.io/library/nextcloud
  newTag: 33.0.2-fpm
- name: docker.io/bitnamilegacy/mariadb
  newTag: 12.0.2
- name: docker.io/bitnamilegacy/redis
  newTag: 8.2.1
patches:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: nextcloud
  target:
    name: nextcloud(-nginxconfig|-phpconfig)?
    kind: ConfigMap|Service|Deployment
resources:
- nextcloud-files-pvc.yaml
- hpa.yaml
