---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
helmCharts:
- name: nextcloud
  repo: https://nextcloud.github.io/helm/
  releaseName: nextcloud
  namespace: nextcloud
  version: 6.6.10
  valuesFile: values.yaml
  valuesMerge: override
images:
- name: nextcloud
  newTag: 31.0.14-fpm
- name: docker.io/bitnami/mariadb
  newTag: latest
- name: docker.io/bitnami/redis
  newTag: latest
patches:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: nextcloud
  target:
    name: nextcloud(-nginxconfig|-phpconfig)?
    kind: ConfigMap|Service|Deployment|HorizontalPodAutoscaler
resources:
- nextcloud-files-pvc.yaml
