---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-files-pvc
  namespace: nextcloud
spec:
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      target-app: nextcloud-files
