---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana
    creationPolicy: Owner
  data:
  - secretKey: GF_SECURITY_ADMIN_USER
    remoteRef:
      key: monitoring-grafana
      property: GF_SECURITY_ADMIN_USER
  - secretKey: GF_SECURITY_ADMIN_PASSWORD
    remoteRef:
      key: monitoring-grafana
      property: GF_SECURITY_ADMIN_PASSWORD
