---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
- name: kube-prometheus-stack
  repo: oci://ghcr.io/prometheus-community/charts
  version: 83.4.0
  releaseName: kube-prometheus-stack
  namespace: monitoring
  valuesFile: values.yaml
  valuesMerge: override
  includeCRDs: true
- name: loki
  repo: https://grafana.github.io/helm-charts
  version: 7.0.0
  releaseName: loki
  namespace: monitoring
  valuesFile: loki-values.yaml
  valuesMerge: override
- name: promtail
  repo: https://grafana.github.io/helm-charts
  version: 6.17.1
  releaseName: promtail
  namespace: monitoring
  valuesFile: promtail-values.yaml
  valuesMerge: override
resources:
- grafana-pvc.yaml
