---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s
spec:
  sourceRepos:
  - 'https://github.com/ITK13201/k8s.git'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
