apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-files-pv
  labels:
    target-app: nextcloud-files
spec:
  capacity:
    storage: 16Gi
  local:
    path: /srv/data/k8s/pv/nextcloud/files
