---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gomi-no-hi-backend-secret
  namespace: gomi-no-hi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gomi-no-hi-backend-secret
    creationPolicy: Owner
  data:
  - secretKey: VAPID_PUBLIC_KEY
    remoteRef:
      key: gomi-no-hi-secret
      property: VAPID_PUBLIC_KEY
  - secretKey: VAPID_PRIVATE_KEY
    remoteRef:
      key: gomi-no-hi-secret
      property: VAPID_PRIVATE_KEY
  - secretKey: VAPID_SUBJECT
    remoteRef:
      key: gomi-no-hi-secret
      property: VAPID_SUBJECT
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: gomi-no-hi-secret
      property: REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gomi-no-hi-redis-secret
  namespace: gomi-no-hi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gomi-no-hi-redis-secret
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: gomi-no-hi-redis-secret
      property: REDIS_PASSWORD
