---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gomi-no-hi
resources:
- external-secret.yaml
- ingress-tailscale.yaml
helmCharts:
- name: gomi-no-hi
  repo: oci://ghcr.io/itk13201
  version: 0.1.2
  releaseName: gomi-no-hi
  namespace: gomi-no-hi
  valuesFile: values.yaml
  valuesMerge: override
