---
frontend:
  image:
    repository: ghcr.io/itk13201/gomi-no-hi-frontend
    tag: "2.0.5"
backend:
  image:
    repository: ghcr.io/itk13201/gomi-no-hi-backend
    tag: "2.0.5"
  existingSecret: gomi-no-hi-backend-secret
redis:
  host: gomi-no-hi-redis
  auth:
    existingSecret: gomi-no-hi-redis-secret
  persistence:
    storageClass: manual
    size: 1Gi
