---
- name: Fetch kubeconfig from control plane to localhost
  hosts: control_plane
  become: true
  tasks:
    - name: Fetch kubeconfig to localhost
      ansible.builtin.fetch:
        src: /root/.kube/config
        dest: "~/.kube/config"
        flat: true
        mode: "0600"
