---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rss-generator-cm
data:
  TZ: "Asia/Tokyo"
  PORT: "80"
  DEBUG: "0"
  SELENIUM_SERVER_URL: "http://selenium-hub:4444/wd/hub"
  DATABASE_USER: "rss"
  DATABASE_HOST: "mariadb"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "rss"
