---
apiVersion: v1
kind: Service
metadata:
  name: rss-generator
  labels:
    app: rss-generator
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rss-generator
