---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: growi
  name: mongoexport-backup
spec:
  schedule: "30 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          restartPolicy: OnFailure
          containers:
          - name: mongoexport-backup
            image: bitnami/mongodb
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            args:
            - |
              TIMESTAMP=$(date +%Y%m%d%H%M%S) \
              && mongoexport \
                  --uri=${MONGO_URI} \
                  --collection=revisions \
                  --out=/backup/growi-revisions-${TIMESTAMP}.json \
              && mongoexport \
                  --uri=${MONGO_URI} \
                  --collection=attachments \
                  --out=/backup/growi-attachments-${TIMESTAMP}.json
            env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: growi-secret
                  key: MONGO_URI
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: mongoexport-backup-pvc
