## @param fullnameOverride String to fully override sealed-secrets.fullname
fullnameOverride: sealed-secrets-controller

## Sealed Secret resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## @param resources.limits [object] The resources limits for the Sealed Secret containers
## @param resources.requests [object] The requested resources for the Sealed Secret containers
##
resources:
  requests:
    cpu: 125m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
