---
- hosts: k8s
  become: true
  vars:
    project_dir: "{{ playbook_dir }}/.."
  tasks:
    - name: Create user
      user:
        name: k8s
        state: present
      become: true
    - name: Create ansible directory
      file:
        path: "/ansible"
        state: directory
        owner: "k8s"
        group: "k8s"
        mode: "775"
    - name: Copy shell scripts for initialization
      copy:
        src: "./scripts/"
        dest: /ansible/scripts/
        owner: "k8s"
        group: "k8s"
        mode: "775"
    - name: Setup basic environment
      shell: bash /k8s/scripts/setup_basic_environment.sh
      register: result
      changed_when: result.rc == 1
      failed_when: result.rc > 1
    - name: Deploy SSH Public Key
      authorized_key:
        user: k8s
        state: present
        key: "{{ lookup('file', '/home/itk/.ssh/vagrant/k8s/id_rsa.pub') }}"
      become: true
