---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: moneyrabbit-mariadb-secret
  namespace: moneyrabbit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: moneyrabbit-mariadb-secret
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: moneyrabbit-mariadb-secret
      property: MYSQL_ROOT_PASSWORD
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: moneyrabbit-mariadb-secret
      property: MYSQL_PASSWORD
  - secretKey: MYSQL_USER
    remoteRef:
      key: moneyrabbit-mariadb-secret
      property: MYSQL_USER
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: moneyrabbit-mariadb-secret
      property: MYSQL_DATABASE
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: moneyrabbit-secret
  namespace: moneyrabbit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: moneyrabbit-secret
    creationPolicy: Owner
  data:
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: moneyrabbit-secret
      property: ANTHROPIC_API_KEY
  - secretKey: DATABASE_URL
    remoteRef:
      key: moneyrabbit-secret
      property: DATABASE_URL
