---
frontend:
  image:
    tag: "1.0.3"

backend:
  image:
    tag: "1.0.3"
  existingSecret: moneyrabbit-secret

mariadb:
  auth:
    existingSecret: moneyrabbit-mariadb-secret
  persistence:
    enabled: true
    storageClass: manual
    size: 20Gi
