---
- name: Create temporary directory for ArgoCD manifests
  ansible.builtin.tempfile:
    state: directory
    suffix: argocd
  register: argocd_tmp_dir

- name: Copy ArgoCD manifests
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../manifests/argocd/"
    dest: "{{ argocd_tmp_dir.path }}/"
    mode: "0644"

- name: Apply ArgoCD manifests with Kustomize
  ansible.builtin.command: kubectl apply -k {{ argocd_tmp_dir.path }}
  environment:
    KUBECONFIG: "{{ k8s_kubeconfig_dir }}/config"
  register: argocd_result
  changed_when: "'created' in argocd_result.stdout or 'configured' in argocd_result.stdout"

- name: Clean up temporary directory
  ansible.builtin.file:
    path: "{{ argocd_tmp_dir.path }}"
    state: absent