---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-secret
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minecraft-secret
    creationPolicy: Owner
  data:
  - secretKey: rcon-password
    remoteRef:
      key: minecraft-secret
      property: rcon-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secret
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mariadb-secret
    creationPolicy: Owner
  data:
  - secretKey: mariadb-root-password
    remoteRef:
      key: minecraft-mariadb-secret
      property: mariadb-root-password
  - secretKey: mariadb-password
    remoteRef:
      key: minecraft-mariadb-secret
      property: mariadb-password
