---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rss-notifier-mariadb-secret
  namespace: rss-notifier
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rss-notifier-mariadb-secret
    creationPolicy: Owner
  data:
  - secretKey: mariadb-password
    remoteRef:
      key: rss-notifier-mariadb-secret
      property: mariadb-password
  - secretKey: mariadb-root-password
    remoteRef:
      key: rss-notifier-mariadb-secret
      property: mariadb-root-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rss-notifier-secret
  namespace: rss-notifier
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rss-notifier-secret
    creationPolicy: Owner
  data:
  - secretKey: database-password
    remoteRef:
      key: rss-notifier-secret
      property: database-password
  - secretKey: discord-bot-token
    remoteRef:
      key: rss-notifier-secret
      property: discord-bot-token
