---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: growi-secret
  namespace: growi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: growi-secret
    creationPolicy: Owner
  data:
  - secretKey: MONGO_URI
    remoteRef:
      key: growi-secret
      property: MONGO_URI
  - secretKey: PASSWORD_SEED
    remoteRef:
      key: growi-secret
      property: PASSWORD_SEED
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: growi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: mongodb-root-password
    remoteRef:
      key: growi-mongodb-secret
      property: mongodb-root-password
  - secretKey: mongodb-passwords
    remoteRef:
      key: growi-mongodb-secret
      property: mongodb-passwords
