kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-master-pvc
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
  selector:
    matchLabels:
      target-app: growi-elasticsearch-master
