kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
  selector:
    matchLabels:
      target-app: growi-mongodb
