---
plugins: "analysis-kuromoji,analysis-icu"
image:
  registry: docker.io
  repository: bitnami/elasticsearch
  tag: 8.13.2-debian-12-r2
  pullPolicy: IfNotPresent
master:
  masterOnly: true
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  heapSize: 512m
  podSecurityContext:
    enabled: true
    fsGroup: 1000
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  persistence:
    enabled: true
    existingClaim: elasticsearch-master-pvc
data:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  heapSize: 512m
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1000
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  persistence:
    enabled: true
    existingClaim: elasticsearch-data-pvc
